services:
  ecodeli-backend:
    build:
      context: ./backend
    container_name: ecodeli-backend
    env_file:
      - .env.development
    depends_on:
      - ecodeli-mysql
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
  ecodeli-mysql:
    image: mysql:8.0
    container_name: ecodeli-db
    env_file:
      - .env.development
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ecodeli-mysql:/var/lib/mysql

volumes:
  ecodeli-mysql:
