FROM node:23-alpine3.21 AS base

FROM base AS backend

WORKDIR /app/backend

COPY backend/package.json .

RUN npm install

COPY backend backend

EXPOSE 3000

ENTRYPOINT [ "npm" ]
CMD [ "run", "dev" ]


FROM base AS frontend

WORKDIR /app/frontend

COPY frontend/package.json .

RUN npm install

COPY frontend frontend

EXPOSE 5173

ENTRYPOINT [ "npm" ]
CMD [ "run", "dev" ]